-- ============================================================================
-- Global Online Shop — Supabase schema
--
-- HOW TO INSTALL (one time):
--   1. Open https://supabase.com/dashboard → your project
--   2. Left menu → SQL Editor → New query
--   3. Paste this whole file and click RUN
--
-- Tables: products, categories, app_users, orders
-- The app connects with the publishable key, so RLS is opened for the
-- `anon` role (fine for an MVP demo). Harden before real production use
-- (see the note at the bottom).
-- ============================================================================

-- ---------------------------------------------------------------- products --
create table if not exists public.products (
  id                  bigint primary key,
  title               text not null default '',
  brand               text not null default '',
  category            text not null default '',
  description         text not null default '',
  price               numeric not null default 0,
  discount_percentage numeric not null default 0,
  rating              numeric not null default 0,
  stock               integer not null default 0,
  thumbnail           text not null default '',
  images              jsonb not null default '[]'::jsonb,
  status              text not null default 'Active',
  verified            boolean not null default false,
  created_at          timestamptz not null default now()
);

-- Add `verified` to databases created before it existed (idempotent: only
-- runs when the column is missing).
do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_name = 'products' and column_name = 'verified')
  then
    alter table public.products
      add column verified boolean not null default false;
  end if;
end $$;

-- -------------------------------------------------------------- categories --
create table if not exists public.categories (
  slug        text primary key,
  name        text not null default '',
  url         text not null default '',
  description text not null default '',
  image       text not null default '',
  created_at  timestamptz not null default now()
);

-- ---------------------------------------------------------------- app_users --
-- Shop accounts (NOT Supabase auth.users). Passwords are stored as a
-- SHA-256 hash computed by the app, never in plain text.
create table if not exists public.app_users (
  username      text primary key,
  first_name    text not null default '',
  last_name     text not null default '',
  email         text not null default '',
  phone         text not null default '',
  image         text not null default '',
  provider      text not null default 'local', -- local | google | telegram
  is_admin      boolean not null default false,
  password_hash text,
  created_at    timestamptz not null default now()
);

-- ------------------------------------------------------------------ orders --
create table if not exists public.orders (
  id         text primary key,
  owner      text not null default '',
  status     text not null default 'Processing',
  total      numeric not null default 0,
  address    text not null default '',
  items      jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

-- -------------------------------------------------------------- feedback --
-- Feedback written by shoppers and reviewed by the admin panel. The id is
-- auto-generated so the app can insert without an explicit id.
create table if not exists public.feedback (
  id         bigint generated by default as identity primary key,
  owner      text not null default '',
  name       text not null default '',
  message    text not null default '',
  rating     integer not null default 5,
  created_at timestamptz not null default now()
);

-- ------------------------------------------------------------------- RLS ----
alter table public.products   enable row level security;
alter table public.categories enable row level security;
alter table public.app_users  enable row level security;
alter table public.orders     enable row level security;
alter table public.feedback   enable row level security;

do $$
declare t text;
begin
  foreach t in array array['products', 'categories', 'app_users', 'orders', 'feedback'] loop
    execute format('drop policy if exists "public_full_access" on public.%I', t);
    execute format(
      'create policy "public_full_access" on public.%I for all to anon, authenticated using (true) with check (true)', t);
  end loop;
end $$;

-- ---------------------------------------------------------------- realtime --
-- Lets the admin panel receive NEW feedback instantly (no refresh) and
-- pushes live Users-page updates (new accounts) to the admin plus instant
-- "your account was deleted" events to signed-in shoppers. Safe to re-run:
-- it only alters the publication membership.
alter publication supabase_realtime add table public.feedback;
alter publication supabase_realtime add table public.app_users;
alter publication supabase_realtime add table public.orders;

-- Refresh PostgREST's schema cache so brand-new tables are visible to the
-- API immediately after this script runs.
notify pgrst, 'reload schema';

-- ---------------------------------------------------------------------------
-- PRODUCTION HARDENING (do this before real customers):
--   * Drop the permissive policies above and write scoped ones, e.g.:
--       create policy "anyone can read products" on public.products
--         for select using (true);
--       create policy "only admins write products" on public.products
--         for all using (auth.jwt() ->> 'role' = 'admin');
--   * Move sign-in to Supabase Auth (auth.users) instead of the app_users
--     table, and verify admins with a JWT claim.
-- ---------------------------------------------------------------------------
